In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [51]:
# Get data
data_train = np.loadtxt("TrainData.csv", delimiter=",")
data = tf.convert_to_tensor(data_train,dtype=tf.float32)

t = tf.constant([0, 1/3, 2/3, 1])

#slices = tf.data.Dataset.from_tensor_slices(data_train)
#next_item = slices.make_one_shot_iterator().get_next()

In [52]:
print(data)
print(t)

x = np.matrix([[1], [2], [3],[4]])
print(x)
x = np.reshape(x,(2,2),order='F')
print(x)
print(np.transpose(x)*x)

Tensor("Const_4:0", shape=(8, 10), dtype=float32)
Tensor("Const_5:0", shape=(4,), dtype=float32)
[[1]
 [2]
 [3]
 [4]]
[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]]


In [148]:
def BDF2(U,dt,g,c):
    C = [[1+g, -dt],[np.power(c,2)*dt, 1+g]]
    Un = np.matmul(np.linalg.inv(C),((1+2*g)*U[:,1]-g*U[:,0]))
    Un = Un
    return Un

def evalU(Umat,dt,g,c,I):
    Us = np.zeros((2,I))
    for i in range(0,I):
        Um = np.reshape(Umat[range(0,4),i],(2,2),order='F')
        Us[:,i] = BDF2(Um,dt,g,c)
            
    Umat = np.vstack((Umat,Us))    
    return Umat

def Loss(pred,true):
    e = pred-true
    return (1/2)*np.transpose(e)*e
    

In [149]:
dt = 1/3
g=0.5
c=1
Um = np.reshape(data_train[range(0,4),0],(2,2),order='F')

Us = BDF2(Um,dt,g,c)
print(Us)

[ 0.35620588 -0.27570353]


In [161]:
dt = 1/3
g=0.5
c=1
I=10
Us = evalU(data_train[range(0,4),:],dt,g,c,I)
print(Us)

[[ 0.45054     0.083821    0.22898     0.91334     0.15238     0.82582
   0.53834     0.99613     0.078176    0.44268   ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.42574     0.079208    0.21637     0.86306     0.14399     0.78036
   0.50871     0.9413      0.073873    0.41831   ]
 [-0.14741    -0.027426   -0.07492    -0.29884    -0.049857   -0.2702
  -0.17614    -0.32593    -0.025579   -0.14484   ]
 [ 0.35620588  0.06627145  0.18102847  0.72209576  0.12047167  0.65290518
   0.42562518  0.78755965  0.06180748  0.34998776]
 [-0.27570353 -0.05129499 -0.14012188 -0.55891906 -0.09324748 -0.50535671
  -0.32943671 -0.60958659 -0.04784033 -0.27089506]]


In [162]:
Utrue = data_train[4,:]
Upred = Us[4,:]
error = Utrue-Upred
loss = (1/2)*np.dot(np.transpose(error),error)
print(Utrue.shape)
print(Upred.shape)
print(Utrue-Upred)
print(loss)

(10,)
(10,)
[-0.00213588 -0.00039745 -0.00107847 -0.00431576 -0.00072167 -0.00390518
 -0.00254518 -0.00470965 -0.00037048 -0.00208776]
3.671740521342551e-05


In [ ]:
plt.plot(t,data,'r.')
plt.title('Using ANN as a precondtitioner')
plt.xlabel('Iterations')
plt.ylabel('||e||_2')
#plt.legend(labels=['M_train=100','M_train=50','M_train=20','M_train=10','M_train=5'],loc='best')
#plt.savefig('convergenceReg.eps', format='eps', dpi=1000)
plt.show()